name: tech2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  adaptive_action_sheet: ^2.0.2
  amplify_auth_cognito: ^1.0.0-next.2
  amplify_flutter: ^1.0.0-next.2
  camera: ^0.10.0+4
  carousel_slider: ^4.1.1
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.5
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_speed_dial: ^6.2.0
  google_maps_flutter: ^2.1.7
  google_maps_flutter_web: ^0.4.0+3
  http: ^0.13.4
  http_interceptor: ^1.0.2
  image_picker: ^0.8.6
  image_picker_for_web: ^2.1.10
  intl: ^0.17.0
  mask_text_input_formatter: ^2.4.0
  multi_select_flutter: ^4.1.3
  open_filex: ^4.3.2
  path: ^1.8.2
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  sqflite: ^2.2.4+1
  syncfusion_flutter_datepicker: ^20.3.60

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.21.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
